linters:
  enable:
    - revive
    - goimports
    - exportloopref
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - bodyclose
    - misspell
    - unused
  disable:
    - errcheck
run:
  deadline: 5m
