# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  golangci:
    name: lint
    runs-on: gha-runner-x64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: v1.20
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

  build:
    name: build
    runs-on: gha-runner-x64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

  test:
    if: github.repository_owner == 'zerotier'
    name: test
    runs-on: gha-runner-x64
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      env:
        ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      run: |
        go test -v ./...
